---
version: 2.1

jobs:

  checkov:
    docker:
      - image: python@sha256:364ee1a9e029fb7b60102ae56ff52153ccc929ceab9aa387402fe738432d24cc
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: checkov-{{ .Environment.CHECKOV_VERSION }}
      - run:
          name: Install Checkov
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install checkov
      - save_cache:
          key: checkov-{{ .Environment.CHECKOV_VERSION }}
          paths:
            - ".venv"
      - run:
          name: Run Checkov against repo
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd ~/repo/
            checkov -d . --skip-check CKV_CIRCLECIPIPELINES_2,CKV_DOCKER_8,CKV_CIRCLECIPIPELINES_6

  git-leaks:
    machine:
      image: ubuntu-2204:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Scan for gitLeaks
          command: |
            docker run -v ~/repo:/path zricethezav/gitleaks:latest detect --source="/path" -v

  linting:
    docker:
      - image: python@sha256:364ee1a9e029fb7b60102ae56ff52153ccc929ceab9aa387402fe738432d24cc
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Ubuntu packages
          command: |
            export DEBIAN_FRONTEND='noninteractive'
            apt-get update
      - restore_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}
      - run:
          name: Install Python
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install flake8
            pip install yamllint
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}
          paths:
            - ".venv"
      - run:
          name: Lint repo with yamllint
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd ~/repo
            python3 -m yamllint -c .yamllint.conf .
      - run:
          name: Lint BackEnd with flake8
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd ~/repo/scrubfu
            flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  
workflows:
  version: 2
  untagged_build_test:
    jobs:
      - linting
      - git-leaks
      - checkov
  # tagged_deploy:
  #   jobs:
  #     - publish-pg_scrubfu:
  #         filters:
  #           branches:
  #             ignore: /.*/
  #           tags:
  #             only: /^.*/
